http:
  routers:
    docker_manager_http:
      rule: "Host(\`docker-manager.invento.live\`)"
      entryPoints:
        - web
      service: docker_manager_svc
    docker_manager_https:
      rule: "Host(\`docker-manager.invento.live\`)"
      entryPoints:
        - websecure
      service: docker_manager_svc
      tls:
        certResolver: letsencrypt
  services:
    docker_manager_svc:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:5000"



# ip route show default | awk '/default/ {print $3}'